services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flowstorage-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  sales-db:
    image: postgres:16
    environment:
      POSTGRES_DB: sales_db
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432"
    volumes:
      - sales_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sales_user -d sales_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  sales-service:
    build:
      context: ./services/sales-service
    ports:
      - "8002:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_EXCHANGE: flowstorage.events
    volumes:
      - ./services/sales-service:/app
    depends_on:
      sales-db:
        condition: service_healthy
      inventory-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
        
  auth-db:
    image: postgres:16
    container_name: flowstorage-auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./services/auth-service
    container_name: flowstorage-auth-service
    ports:
      - "8001:8001"
    volumes:
      - ./services/auth-service/app:/app/app
    depends_on:
      auth-db:
        condition: service_healthy

  inventory-db:
    image: postgres:16
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5435:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  inventory-service:
    build:
      context: ./services/inventory-service
    ports:
      - "8003:8000"
      - "50051:50051"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_EXCHANGE: flowstorage.events
    volumes:
      - ./services/inventory-service:/app
    depends_on:
      inventory-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  replacement-db:
    image: postgres:16
    environment:
      POSTGRES_DB: replacement_db
      POSTGRES_USER: replacement_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5436:5432"
    volumes:
      - replacement_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U replacement_user -d replacement_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  replacement-service:
    build:
      context: ./services/replacement-service
    ports:
      - "8004:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_EXCHANGE: flowstorage.events
      RABBITMQ_QUEUE: replacement-service.stock-low
      RABBITMQ_ROUTING_KEYS: stock.low
      AUTOMATIC_REORDER_FALLBACK_SUPPLIER: Fornecedor pendente
    volumes:
      - ./services/replacement-service/app:/app/app
    depends_on:
      replacement-db:
        condition: service_healthy
      inventory-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  notification-db:
    image: postgres:16
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5437:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification_user -d notification_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  notification-service:
    build:
      context: ./services/notification-service
    ports:
      - "8005:8000"
    environment:
      DATABASE_URL: postgresql://notification_user:123456@notification-db:5432/notification_db
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_EXCHANGE: flowstorage.events
      RABBITMQ_QUEUE: notification-service.stock
      RABBITMQ_ROUTING_KEYS: sales.created,stock.updated,stock.increased,stock.decreased,replacement.received,stock.low,stock.critical
      GLOBAL_NOTIFICATION_USER_ID: "1"
    volumes:
      - ./services/notification-service/app:/app/app
    depends_on:
      notification-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

volumes:
  auth_db_data:
  inventory_db_data:
  sales_db_data:
  replacement_db_data:
  notification_db_data:
  rabbitmq_data:
