# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"$\n\x0eProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\"x\n\x0fProductResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0c\n\x04nome\x18\x03 \x01(\t\x12\x0b\n\x03sku\x18\x04 \x01(\t\x12\r\n\x05preco\x18\x05 \x01(\x01\x12\x0f\n\x07\x65stoque\x18\x06 \x01(\x05\x12\x0f\n\x07message\x18\x07 \x01(\t\"<\n\x14\x44\x65\x63reaseStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"H\n\rStockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x15\n\rcurrent_stock\x18\x03 \x01(\x05\x32{\n\x10InventoryService\x12/\n\nGetProduct\x12\x0f.ProductRequest\x1a\x10.ProductResponse\x12\x36\n\rDecreaseStock\x12\x15.DecreaseStockRequest\x1a\x0e.StockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTREQUEST']._serialized_start=19
  _globals['_PRODUCTREQUEST']._serialized_end=55
  _globals['_PRODUCTRESPONSE']._serialized_start=57
  _globals['_PRODUCTRESPONSE']._serialized_end=177
  _globals['_DECREASESTOCKREQUEST']._serialized_start=179
  _globals['_DECREASESTOCKREQUEST']._serialized_end=239
  _globals['_STOCKRESPONSE']._serialized_start=241
  _globals['_STOCKRESPONSE']._serialized_end=313
  _globals['_INVENTORYSERVICE']._serialized_start=315
  _globals['_INVENTORYSERVICE']._serialized_end=438
# @@protoc_insertion_point(module_scope)
